Repository KAU-SMART-PETS/Capstone_BE, pull requests merged in 2024-11, with the labels that each got.

#166 refactor: 소셜 로그인/로그아웃 리다이렉트 제거
  src/main/java/com/kau/capstone/domain/auth/controller/AuthApi.java
  src/main/java/com/kau/capstone/domain/auth/controller/AuthController.java
Labels: 🔧 Refactor

#172 fix: 삭제된 pet 조회 안되게 처리
  src/main/java/com/kau/capstone/domain/member/service/MemberService.java
Labels: 🐛 Bug

#174 fix: pet 이미지 유무에 따른 로직 처리
  src/main/java/com/kau/capstone/domain/pet/service/PetService.java
Labels: 🐛 Bug

#176 bug: 반려동물 목록 조회시 삭제된 반려동물 제외
  src/main/java/com/kau/capstone/domain/member/service/MemberService.java
Labels: 🐛 Bug

#180 refactor: 세션 유지 시간을 늘리도록 변경
  src/main/resources/application-prod.yml
Labels: 🔧 Refactor

#182 fix: pet name 등록 시 대문자 영문도 허용
  src/main/java/com/kau/capstone/domain/pet/dto/request/PetRegistRequest.java
Labels: 🐛 Bug

#192 feat: regist pet nose
  src/main/java/com/kau/capstone/domain/ai/client/AIModelClient.java
  src/main/java/com/kau/capstone/domain/ai/controller/AIController.java
  src/main/java/com/kau/capstone/domain/ai/service/AIService.java
Labels: ✨ Feature

#194 fix: 파일 전송 용량 수정
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 🐛 Bug

#203 feat: test nose
  src/main/java/com/kau/capstone/domain/ai/client/AIModelClient.java
  src/main/java/com/kau/capstone/domain/ai/controller/AIController.java
  src/main/java/com/kau/capstone/domain/ai/service/AIService.java
Labels: ✨ Feature
