Repository KAU-SMART-PETS/Capstone_BE, pull requests merged in 2024-05, with the labels that each got.

#5 infra: Docker 파일 생성
  Dockerfile
  build.gradle
Labels: 🌎 Infra

#10 [CHORE] h2 의존성 추가 및 기존 의존성 정리
  build.gradle
Labels: ⚙️ Chore

#14 [FEAT] CICD 스크립트 작성
  .github/workflows/deploy.yml
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  src/main/resources/application-prod.yml
  src/test/resources/application.yml
Labels: ✨ Feature

#6 [FEAT] 반려동물 등록 api 생성
  src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
  src/main/java/com/kau/capstone/domain/pet/dto/request/PetRegistRequest.java
  src/main/java/com/kau/capstone/domain/pet/entity/Pet.java
  src/main/java/com/kau/capstone/domain/pet/repository/PetRepository.java
  src/main/java/com/kau/capstone/domain/pet/service/PetService.java
  src/main/java/com/kau/capstone/domain/pet/util/PetMapper.java
  src/main/java/com/kau/capstone/global/common/BaseEntity.java
  src/main/java/com/kau/capstone/global/common/Gender.java
  src/main/java/com/kau/capstone/global/common/PetType.java
  src/main/java/com/kau/capstone/global/exception/ErrorCode.java
  src/main/java/com/kau/capstone/global/exception/InvalidGenderException.java
  src/main/java/com/kau/capstone/global/exception/NotExistPetTypeException.java
Labels: ✨ Feature

#12 [FEAT] 임시 로그인 기능 추가
  src/main/java/com/kau/capstone/domain/auth/controller/AuthController.java
  src/main/java/com/kau/capstone/domain/auth/dto/LoginInfo.java
  src/main/java/com/kau/capstone/domain/auth/exception/AuthException.java
  src/main/java/com/kau/capstone/domain/auth/service/AuthService.java
  src/main/java/com/kau/capstone/domain/auth/util/AuthArgumentResolver.java
  src/main/java/com/kau/capstone/domain/auth/util/AuthHandlerInterceptor.java
  src/main/java/com/kau/capstone/domain/auth/util/LoginUser.java
  src/main/java/com/kau/capstone/global/common/WebConfig.java
  src/main/java/com/kau/capstone/global/exception/ErrorCode.java
Labels: ✨ Feature

#21 fix: CI 실행시 PR에서 수정된 application.yml 코드가 적용되지 않는 버그 수정
  .github/workflows/gradle.yml
Labels: 🐛 Bug

#17 [FEAT] 카카오 소셜 로그인 추가
  src/main/java/com/kau/capstone/CapstoneApplication.java
  src/main/java/com/kau/capstone/domain/auth/controller/AuthController.java
  src/main/java/com/kau/capstone/domain/auth/dto/KakaoAccessTokenResponse.java
  src/main/java/com/kau/capstone/domain/auth/dto/KakaoUserInfoResponse.java
  src/main/java/com/kau/capstone/domain/auth/dto/SignUserDto.java
  src/main/java/com/kau/capstone/domain/auth/dto/UserInfoDto.java
  src/main/java/com/kau/capstone/domain/auth/service/AuthService.java
  src/main/java/com/kau/capstone/domain/auth/util/AuthConfig.java
  src/main/java/com/kau/capstone/domain/auth/util/SocialSite.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/KakaoProvider.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/OAuthProvider.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/OAuthProviders.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/access/KakaoAccessToken.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/logout/KakaoLogout.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/redirect/KakaoRedirect.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/secret/KakaoSecretValue.java
  src/main/java/com/kau/capstone/domain/member/entity/Member.java
  src/main/java/com/kau/capstone/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/kau/capstone/domain/member/repository/MemberRepository.java
  src/main/java/com/kau/capstone/domain/member/service/MemberService.java
  src/main/java/com/kau/capstone/domain/member/util/MemberMapper.java
  src/main/java/com/kau/capstone/global/exception/ErrorCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/resources/application.yml
Labels: ✨ Feature

#22 [FEAT]네이버 소셜 로그인 추가
  src/main/java/com/kau/capstone/domain/auth/dto/NaverAccessTokenResponse.java
  src/main/java/com/kau/capstone/domain/auth/dto/NaverUserInfoResponse.java
  src/main/java/com/kau/capstone/domain/auth/util/SocialSite.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/NaverProvider.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/access/NaverAccessToken.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/logout/NaverLogout.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/redirect/NaverRedirect.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/secret/NaverSecretValue.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: ✨ Feature

#24 [REFACTOR] 소셜 로그아웃 방식 변경, 리프레시 토큰 갱신 추가
  src/main/java/com/kau/capstone/domain/auth/controller/AuthController.java
  src/main/java/com/kau/capstone/domain/auth/dto/KakaoUserInfoResponse.java
  src/main/java/com/kau/capstone/domain/auth/dto/NaverUserInfoResponse.java
  src/main/java/com/kau/capstone/domain/auth/dto/TokenInfo.java
  src/main/java/com/kau/capstone/domain/auth/dto/UserInfoDto.java
  src/main/java/com/kau/capstone/domain/auth/service/AuthService.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/KakaoProvider.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/NaverProvider.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/OAuthProvider.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/access/KakaoAccessToken.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/access/NaverAccessToken.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/logout/KakaoLogout.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/logout/NaverLogout.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/refresh/KakaoRefreshToken.java
  src/main/java/com/kau/capstone/domain/auth/util/provider/refresh/NaverRefreshToken.java
  src/main/java/com/kau/capstone/domain/member/entity/Member.java
  src/main/java/com/kau/capstone/domain/member/repository/MemberRepository.java
  src/main/java/com/kau/capstone/domain/member/service/MemberService.java
  src/main/java/com/kau/capstone/domain/member/util/MemberMapper.java
Labels: 🔧 Refactor
