Repository KAU-SMART-PETS/Capstone_BE, pull requests merged in 2024-10, with the labels that each got.

#49 test: 유저 단위 테스트 추가
  src/test/java/com/kau/capstone/domain/member/entity/MemberTest.java
Labels: 💻 Test

#48 feat: 유저가 반려동물 등록시 유저와 반려동물 정보를 연결
  src/main/java/com/kau/capstone/domain/member/entity/Member.java
  src/main/java/com/kau/capstone/domain/member/entity/pet/OwnedPet.java
  src/main/java/com/kau/capstone/domain/member/repository/OwnedPetRepository.java
  src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
  src/main/java/com/kau/capstone/domain/pet/service/PetService.java
Labels: ✨ Feature

#51 refactor: pet 도메인 리팩토링
  build.gradle
  src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
  src/main/java/com/kau/capstone/domain/pet/dto/request/PetRegistRequest.java
  src/main/java/com/kau/capstone/domain/pet/dto/request/UpdatePetInfoRequest.java
  src/main/java/com/kau/capstone/domain/pet/dto/response/PetInfoResponse.java
  src/main/java/com/kau/capstone/domain/pet/entity/Pet.java
  src/main/java/com/kau/capstone/domain/pet/service/PetService.java
  src/main/java/com/kau/capstone/domain/pet/util/PetMapper.java
  src/main/java/com/kau/capstone/global/common/s3/S3Service.java
  src/main/java/com/kau/capstone/global/common/s3/exception/CannotConvertFileException.java
  src/main/java/com/kau/capstone/global/config/S3Config.java
  src/main/java/com/kau/capstone/global/exception/ErrorCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/resources/application.yml
Labels: 🔧 Refactor

#50 test: 유저 E2E 테스트 추가
  build.gradle
  src/main/java/com/kau/capstone/domain/auth/util/SocialSite.java
  src/test/java/com/kau/capstone/common/TestProvider.java
  src/test/java/com/kau/capstone/common/access/TestAccessToken.java
  src/test/java/com/kau/capstone/common/logout/TestLogout.java
  src/test/java/com/kau/capstone/common/redirect/TestRedirect.java
  src/test/java/com/kau/capstone/common/refresh/TestRefreshToken.java
  src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java
  src/test/java/com/kau/capstone/domain/member/service/TestMemberService.java
  src/test/resources/application.yml
Labels: 💻 Test

#58 bug: pet pathVariable 수정
  src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 🐛 Bug

#62 fix: 프로덕션 로직 업데이트로 인한 TestMemberService 로직 수정
  src/test/java/com/kau/capstone/domain/member/service/TestMemberService.java
Labels: 🐛 Bug

#64 fix: deploy 코드 복구
  .github/workflows/deploy.yml
Labels: 🐛 Bug

#67 feat: 동물 병원과 사용자 사이의 거리를 제공하는 값 추가
  src/main/java/com/kau/capstone/domain/vet/controller/VetController.java
  src/main/java/com/kau/capstone/domain/vet/dto/MemberLocationRequest.java
  src/main/java/com/kau/capstone/domain/vet/dto/VetDetailResponse.java
  src/main/java/com/kau/capstone/domain/vet/entity/Vet.java
  src/main/java/com/kau/capstone/domain/vet/service/VetService.java
Labels: ✨ Feature

#69 refactor: 동물병원 목록 API 응답 데이터 수정
  src/main/java/com/kau/capstone/domain/vet/controller/VetController.java
  src/main/java/com/kau/capstone/domain/vet/dto/VetResponse.java
Labels: ✨ Feature

#81 refactor: 사용자 기능 API 업데이트
  src/main/java/com/kau/capstone/domain/member/controller/MemberController.java
  src/main/java/com/kau/capstone/domain/member/dto/MemberInfoResponse.java
  src/main/java/com/kau/capstone/domain/member/dto/ModifyMemberRequest.java
  src/main/java/com/kau/capstone/domain/member/entity/Member.java
  src/main/java/com/kau/capstone/domain/member/service/MemberService.java
  src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java
  src/test/java/com/kau/capstone/domain/member/entity/MemberTest.java
Labels: 🔧 Refactor

#82 feat: 사용자, 반려동물 경로에 로그인 인터셉터 추가
  src/main/java/com/kau/capstone/global/common/WebConfig.java
Labels: ✨ Feature

#83 [feat] 동물병원 Swagger 문서 추가
  src/main/java/com/kau/capstone/domain/auth/controller/AuthController.java
  src/main/java/com/kau/capstone/domain/member/controller/MemberController.java
  src/main/java/com/kau/capstone/domain/vet/controller/VetApi.java
  src/main/java/com/kau/capstone/domain/vet/controller/VetController.java
Labels: ✨ Feature

#84 feat: 포인트 결제 기능 추가
  src/main/java/com/kau/capstone/domain/member/controller/MemberController.java
  src/main/java/com/kau/capstone/domain/member/dto/PayPointRequest.java
  src/main/java/com/kau/capstone/domain/member/entity/Member.java
  src/main/java/com/kau/capstone/domain/member/exception/PointNotEnoughException.java
  src/main/java/com/kau/capstone/domain/member/service/MemberService.java
  src/main/java/com/kau/capstone/global/exception/ErrorCode.java
  src/test/java/com/kau/capstone/domain/member/entity/MemberTest.java
Labels: ✨ Feature

#85 feat: 사료 엔티티 추가
  src/main/java/com/kau/capstone/domain/food/entity/Food.java
Labels: ✨ Feature

#86 feat: 사료 목록 조회 API 추가
  src/main/java/com/kau/capstone/domain/food/controller/FoodController.java
  src/main/java/com/kau/capstone/domain/food/dto/FoodResponse.java
  src/main/java/com/kau/capstone/domain/food/dto/FoodsResponse.java
  src/main/java/com/kau/capstone/domain/food/repository/FoodRepository.java
  src/main/java/com/kau/capstone/domain/food/service/FoodService.java
Labels: ✨ Feature

#92 feat: 포인트 획득 API 추가
  src/main/java/com/kau/capstone/domain/member/controller/MemberController.java
  src/main/java/com/kau/capstone/domain/member/dto/EarnPointRequest.java
  src/main/java/com/kau/capstone/domain/member/entity/Member.java
  src/main/java/com/kau/capstone/domain/member/service/MemberService.java
  src/test/java/com/kau/capstone/domain/member/entity/MemberTest.java
Labels: ✨ Feature

#93 feat: cors 설정 추가
  src/main/java/com/kau/capstone/global/common/WebConfig.java
Labels: ✨ Feature

#94 test: 포인트 결제, 포인트 획득 E2E 테스트 추가
  src/main/java/com/kau/capstone/global/exception/ErrorCode.java
  src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java
Labels: 💻 Test

#96 fix: 트랜잭션 옵션 수정
  src/main/java/com/kau/capstone/domain/auth/service/AuthService.java
  src/main/java/com/kau/capstone/domain/food/service/FoodService.java
  src/main/java/com/kau/capstone/domain/member/service/MemberService.java
  src/main/java/com/kau/capstone/domain/vet/service/VetService.java
Labels: 🐛 Bug

#99 refactor: 패키지 이동 및 코드 리팩터링
  src/main/java/com/kau/capstone/global/exception/GlobalExceptionHandler.java
  src/test/java/com/kau/capstone/domain/auth/TestProvider.java
  src/test/java/com/kau/capstone/domain/auth/access/TestAccessToken.java
  src/test/java/com/kau/capstone/domain/auth/logout/TestLogout.java
  src/test/java/com/kau/capstone/domain/auth/redirect/TestRedirect.java
  src/test/java/com/kau/capstone/domain/auth/refresh/TestRefreshToken.java
  src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java
  src/test/java/com/kau/capstone/domain/member/entity/MemberTest.java
  src/test/java/com/kau/capstone/global/common/ControllerTest.java
Labels: 💻 Test

#100 test: 사용자가 등록한 반려동물 목록 조회 API 테스트 추가
  src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java
  src/test/java/com/kau/capstone/global/common/ControllerTest.java
Labels: 💻 Test

#103 refactor: 유저 정보 조회 API를 수정된 요구사항에 맞게 변경
  src/main/java/com/kau/capstone/domain/member/dto/MemberInfoResponse.java
  src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java
Labels: 🔧 Refactor

#104 test: 포인트 획득 E2E 테스트 추가
  src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java
Labels: 💻 Test

#108 test: 동물병원 관련 기능 E2E 테스트 추가
  src/test/java/com/kau/capstone/domain/vet/controller/VetControllerTest.java
  src/test/java/com/kau/capstone/global/common/ControllerTest.java
Labels: 💻 Test

#109 test: 사료 목록 조회 E2E 테스트 추가
  src/test/java/com/kau/capstone/domain/food/controller/FoodControllerTest.java
  src/test/java/com/kau/capstone/global/common/ControllerTest.java
Labels: 💻 Test

#110 feat: 사용자가 등록한 블루투스 기기 목록 조회 기능 추가
  src/main/java/com/kau/capstone/domain/bluetooth/controller/BluetoothController.java
  src/main/java/com/kau/capstone/domain/bluetooth/dto/OneOwnedBluetoothResponse.java
  src/main/java/com/kau/capstone/domain/bluetooth/dto/OwnedBluetoothResponse.java
  src/main/java/com/kau/capstone/domain/bluetooth/entity/Bluetooth.java
  src/main/java/com/kau/capstone/domain/bluetooth/entity/member/OwnedBluetooth.java
  src/main/java/com/kau/capstone/domain/bluetooth/repository/BluetoothRepository.java
  src/main/java/com/kau/capstone/domain/bluetooth/repository/OwnedBluetoothRepository.java
  src/main/java/com/kau/capstone/domain/bluetooth/service/BluetoothService.java
  src/test/java/com/kau/capstone/domain/bluetooth/controller/BluetoothControllerTest.java
  src/test/java/com/kau/capstone/global/common/ControllerTest.java
Labels: ✨ Feature, 💻 Test

#111 feat: 사용자가 블루투스 기기를 등록할 수 있는 기능 추가
  src/main/java/com/kau/capstone/domain/bluetooth/controller/BluetoothController.java
  src/main/java/com/kau/capstone/domain/bluetooth/dto/BluetoothRegistryRequest.java
  src/main/java/com/kau/capstone/domain/bluetooth/service/BluetoothService.java
  src/test/java/com/kau/capstone/domain/bluetooth/controller/BluetoothControllerTest.java
Labels: ✨ Feature, 💻 Test

#113 refactor: 포인트 기능 리팩터링
  src/main/java/com/kau/capstone/domain/member/controller/MemberController.java
  src/main/java/com/kau/capstone/domain/member/dto/MemberInfoResponse.java
  src/main/java/com/kau/capstone/domain/member/entity/Member.java
  src/main/java/com/kau/capstone/domain/member/service/MemberService.java
  src/main/java/com/kau/capstone/domain/point/controller/PointController.java
  src/main/java/com/kau/capstone/domain/point/dto/EarnPointRequest.java
  src/main/java/com/kau/capstone/domain/point/dto/PayPointRequest.java
  src/main/java/com/kau/capstone/domain/point/entity/Point.java
  src/main/java/com/kau/capstone/domain/point/repository/PointRepository.java
  src/main/java/com/kau/capstone/domain/point/service/PointService.java
  src/test/java/com/kau/capstone/domain/member/controller/MemberControllerTest.java
  src/test/java/com/kau/capstone/domain/member/entity/MemberTest.java
  src/test/java/com/kau/capstone/domain/member/service/TestMemberService.java
  src/test/java/com/kau/capstone/domain/point/controller/PointControllerTest.java
  src/test/java/com/kau/capstone/domain/point/entity/PointTest.java
  src/test/java/com/kau/capstone/global/common/ControllerTest.java
Labels: 🔧 Refactor

#122 feat: 포인트 적립/결제 내역 기능 추가
  src/main/java/com/kau/capstone/domain/point/controller/PointController.java
  src/main/java/com/kau/capstone/domain/point/dto/HistoryResponse.java
  src/main/java/com/kau/capstone/domain/point/dto/OneHistoryResponse.java
  src/main/java/com/kau/capstone/domain/point/entity/history/History.java
  src/main/java/com/kau/capstone/domain/point/repository/HistoryRepository.java
  src/main/java/com/kau/capstone/domain/point/service/PointService.java
  src/test/java/com/kau/capstone/domain/point/controller/PointControllerTest.java
Labels: ✨ Feature, 💻 Test

#123 feat: 사료 결제 기능 추가
  src/main/java/com/kau/capstone/domain/food/controller/FoodController.java
  src/main/java/com/kau/capstone/domain/food/exception/FoodNotFoundException.java
  src/main/java/com/kau/capstone/domain/point/dto/DeliveryFeeRequest.java
  src/main/java/com/kau/capstone/domain/point/service/PointService.java
  src/main/java/com/kau/capstone/global/exception/ErrorCode.java
  src/test/java/com/kau/capstone/domain/food/controller/FoodControllerTest.java
  src/test/java/com/kau/capstone/domain/point/controller/PointControllerTest.java
Labels: ✨ Feature, 💻 Test

#124 refactor: 동물병원 목록 조회시 사용자와 가까운 동물병원 20개 제공으로 API 변경
  src/main/java/com/kau/capstone/domain/vet/controller/VetApi.java
  src/main/java/com/kau/capstone/domain/vet/controller/VetController.java
  src/main/java/com/kau/capstone/domain/vet/entity/Vet.java
  src/main/java/com/kau/capstone/domain/vet/repository/VetRepository.java
  src/main/java/com/kau/capstone/domain/vet/service/VetService.java
  src/test/java/com/kau/capstone/domain/vet/controller/VetControllerTest.java
  src/test/resources/application.yml
Labels: 🔧 Refactor

#126 refactor: 동물병원 스웨거 문서 수정
  src/main/java/com/kau/capstone/domain/vet/controller/VetApi.java
Labels: 🔧 Refactor

#127 feat: 리워드 기능 추가 및 리워드 목록 조회
  src/main/java/com/kau/capstone/domain/bluetooth/service/BluetoothService.java
  src/main/java/com/kau/capstone/domain/member/service/MemberService.java
  src/main/java/com/kau/capstone/domain/pet/service/PetService.java
  src/main/java/com/kau/capstone/domain/point/service/PointService.java
  src/main/java/com/kau/capstone/domain/reward/controller/RewardController.java
  src/main/java/com/kau/capstone/domain/reward/dto/RewardResponse.java
  src/main/java/com/kau/capstone/domain/reward/dto/RewardsResponse.java
  src/main/java/com/kau/capstone/domain/reward/entity/Reward.java
  src/main/java/com/kau/capstone/domain/reward/entity/RewardDetail.java
  src/main/java/com/kau/capstone/domain/reward/repository/RewardRepository.java
  src/main/java/com/kau/capstone/domain/reward/service/RewardService.java
  src/test/java/com/kau/capstone/domain/member/service/TestMemberService.java
  src/test/java/com/kau/capstone/domain/reward/controller/RewardControllerTest.java
Labels: ✨ Feature, 💻 Test

#128 feat: 리워드 달성시 포인트 적립 기능 추가
  src/main/java/com/kau/capstone/domain/point/service/PointService.java
  src/main/java/com/kau/capstone/domain/reward/controller/RewardController.java
  src/main/java/com/kau/capstone/domain/reward/dto/RewardResponse.java
  src/main/java/com/kau/capstone/domain/reward/entity/Reward.java
  src/main/java/com/kau/capstone/domain/reward/exception/RewardNotFoundException.java
  src/main/java/com/kau/capstone/global/exception/ErrorCode.java
  src/test/java/com/kau/capstone/domain/reward/controller/RewardControllerTest.java
Labels: ✨ Feature, 💻 Test

#129 feat: 알람 기능 추가
  src/main/java/com/kau/capstone/domain/alarm/controller/AlarmController.java
  src/main/java/com/kau/capstone/domain/alarm/dto/AlarmResponse.java
  src/main/java/com/kau/capstone/domain/alarm/dto/OneAlarmResponse.java
  src/main/java/com/kau/capstone/domain/alarm/entity/Alarm.java
  src/main/java/com/kau/capstone/domain/alarm/entity/AlarmDetail.java
  src/main/java/com/kau/capstone/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/kau/capstone/domain/alarm/service/AlarmService.java
  src/main/java/com/kau/capstone/domain/member/service/MemberService.java
  src/main/java/com/kau/capstone/domain/pet/service/PetService.java
  src/main/java/com/kau/capstone/domain/point/service/PointService.java
  src/test/java/com/kau/capstone/domain/alarm/controller/AlarmControllerTest.java
  src/test/java/com/kau/capstone/domain/member/service/TestMemberService.java
Labels: ✨ Feature, 💻 Test

#131 feat: 동물병원 목록 조회 HTTP 메서드 변경
  src/main/java/com/kau/capstone/domain/vet/controller/VetApi.java
  src/main/java/com/kau/capstone/domain/vet/controller/VetController.java
  src/test/java/com/kau/capstone/domain/vet/controller/VetControllerTest.java
Labels: 🐛 Bug

#133 fix: 동물병원 세부 목록 조회 HTTP 메서드 변경
  src/main/java/com/kau/capstone/domain/vet/controller/VetApi.java
  src/main/java/com/kau/capstone/domain/vet/controller/VetController.java
  src/test/java/com/kau/capstone/domain/vet/controller/VetControllerTest.java
Labels: 🐛 Bug

#134 feat: 보건정보 기능 CRUD 추가
  src/main/java/com/kau/capstone/domain/vaccination/controller/VaccinationController.java
  src/main/java/com/kau/capstone/domain/vaccination/dto/CreateVaccinationRequest.java
  src/main/java/com/kau/capstone/domain/vaccination/dto/OneVaccinationResponse.java
  src/main/java/com/kau/capstone/domain/vaccination/dto/PetVaccinationResponse.java
  src/main/java/com/kau/capstone/domain/vaccination/dto/PutVaccinationRequest.java
  src/main/java/com/kau/capstone/domain/vaccination/dto/VaccinationsResponse.java
  src/main/java/com/kau/capstone/domain/vaccination/entity/Vaccination.java
  src/main/java/com/kau/capstone/domain/vaccination/exception/VaccinationNotFoundException.java
  src/main/java/com/kau/capstone/domain/vaccination/repository/VaccinationRepository.java
  src/main/java/com/kau/capstone/domain/vaccination/service/VaccinationService.java
  src/main/java/com/kau/capstone/global/exception/ErrorCode.java
  src/test/java/com/kau/capstone/domain/vaccination/controller/VaccinationControllerTest.java
  src/test/java/com/kau/capstone/global/common/ControllerTest.java
Labels: ✨ Feature, 💻 Test

#136 feat: 로그인이 필요한 API 인터셉터 추가
  src/main/java/com/kau/capstone/domain/pet/util/PetHandlerInterceptor.java
  src/main/java/com/kau/capstone/global/common/WebConfig.java
Labels: ✨ Feature

#138 docs: Swagger 문서 업데이트
  src/main/java/com/kau/capstone/domain/alarm/controller/AlarmApi.java
  src/main/java/com/kau/capstone/domain/alarm/controller/AlarmController.java
  src/main/java/com/kau/capstone/domain/auth/controller/AuthApi.java
  src/main/java/com/kau/capstone/domain/auth/controller/AuthController.java
  src/main/java/com/kau/capstone/domain/bluetooth/controller/BluetoothApi.java
  src/main/java/com/kau/capstone/domain/bluetooth/controller/BluetoothController.java
  src/main/java/com/kau/capstone/domain/food/controller/FoodApi.java
  src/main/java/com/kau/capstone/domain/food/controller/FoodController.java
  src/main/java/com/kau/capstone/domain/member/controller/MemberApi.java
  src/main/java/com/kau/capstone/domain/member/controller/MemberController.java
  src/main/java/com/kau/capstone/domain/point/controller/PointApi.java
  src/main/java/com/kau/capstone/domain/point/controller/PointController.java
  src/main/java/com/kau/capstone/domain/reward/controller/RewardApi.java
  src/main/java/com/kau/capstone/domain/reward/controller/RewardController.java
  src/main/java/com/kau/capstone/domain/vaccination/controller/VaccinationApi.java
  src/main/java/com/kau/capstone/domain/vaccination/controller/VaccinationController.java
  src/main/java/com/kau/capstone/domain/vet/controller/VetApi.java
Labels: 📃 Docs

#139 fix: swagger 이름 변경
  src/main/java/com/kau/capstone/domain/member/controller/MemberApi.java
Labels: 🐛 Bug

#141 feat: 소셜 로그인 HTTP 메서드 추가 지원
  src/main/java/com/kau/capstone/domain/auth/controller/AuthController.java
Labels: ✨ Feature

#142 docs: 소셜 로그인 API Swagger 업데이트
  src/main/java/com/kau/capstone/domain/auth/controller/AuthApi.java
Labels: 📃 Docs

#144 fix: 포인트 내역 조회를 최신순으로 볼 수 있도록 수정
  src/main/java/com/kau/capstone/domain/point/repository/HistoryRepository.java
  src/test/java/com/kau/capstone/domain/point/controller/PointControllerTest.java
Labels: 🐛 Bug

#145 fix: 소셜 로그인을 로그아웃할시 로그인 사이트를 찾지 못하는 버그 수정
  src/main/java/com/kau/capstone/domain/auth/util/SocialSite.java
Labels: 🐛 Bug

#146 fix: 소셜 로그인 탐색과 소셜 로그인 링크를 받는 과정에서 발생하는 에러 메시지 분리
  src/main/java/com/kau/capstone/domain/auth/util/SocialSite.java
  src/main/java/com/kau/capstone/global/exception/ErrorCode.java
Labels: 🐛 Bug

#148 feat: 예상하지 못한 에러 발생시 문제 원인을 파악할 수 있도록 메시지 추가
  src/main/java/com/kau/capstone/global/exception/GlobalExceptionHandler.java
Labels: ✨ Feature

#150 fix: 반려동물 등록시 몸무게를 Float > Double로 변경
  src/main/java/com/kau/capstone/domain/pet/dto/request/PetRegistRequest.java
Labels: 🐛 Bug

#152 fix: 보건정보 조회를 예방접종 최신순으로 변경
  src/main/java/com/kau/capstone/domain/vaccination/repository/VaccinationRepository.java
Labels: 🐛 Bug

#155 refactor: 동물병원 세부 조회시 위도, 경도 데이터를 반환하도록 수정
  src/main/java/com/kau/capstone/domain/vet/controller/VetController.java
  src/main/java/com/kau/capstone/domain/vet/dto/VetDetailResponse.java
  src/main/java/com/kau/capstone/domain/vet/service/VetService.java
Labels: 🔧 Refactor

#157 feat: 모바일 결과물 확인을 위한 더미데이터 추가
  src/main/java/com/kau/capstone/initial/FoodInitializer.java
  src/main/java/com/kau/capstone/initial/VetInitializer.java
Labels: 🔧 Refactor

#159 fix: validation 제거
  src/main/java/com/kau/capstone/domain/pet/dto/request/PetRegistRequest.java
Labels: 🐛 Bug

#161 refactor: 백신 id 추가
  src/main/java/com/kau/capstone/domain/vaccination/dto/OneVaccinationResponse.java
Labels: 🔧 Refactor

#163 bug: 기존 유저는 카카오 로그인시 리프레시토큰 정보를 변경할 수 있도록 수정
  src/main/java/com/kau/capstone/domain/member/entity/Member.java
  src/main/java/com/kau/capstone/domain/member/service/MemberService.java
Labels: 🐛 Bug
